From node:16.20.2-aphine3.18
RUN apk update --no-cache
RUN apk add g++ gcc libgcc libstdc++ linux-headers make python3
RUN apk add curl inputils
WORKDIR /backend-api
COPY ./backend-api/login_management ./login_management
COPY ./backend-api/package.json .
RUN npm cache clean --force
RUN npm install
COPY ./backend-api/common ./common
WORKDIR /backend-api/login_management
RUN npm cache clean --force
RUN npm install
CMD ["node", "index.js", "80"]

